# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capirosInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1525, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 881))
        MainWindow.setBaseSize(QtCore.QSize(1, 0))
        MainWindow.setIconSize(QtCore.QSize(70, 70))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(35, -1, 35, -1)
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(20, 60, 20, 60)
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEditId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditId.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditId.sizePolicy().hasHeightForWidth())
        self.lineEditId.setSizePolicy(sizePolicy)
        self.lineEditId.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditId.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditId.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditId.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditId.setObjectName("lineEditId")
        self.horizontalLayout_3.addWidget(self.lineEditId)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(25)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBoxVariedad = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxVariedad.setObjectName("comboBoxVariedad")
        self.comboBoxVariedad.addItem("")
        self.comboBoxVariedad.addItem("")
        self.comboBoxVariedad.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxVariedad)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonInfo.setEnabled(True)
        self.pushButtonInfo.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButtonInfo.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonInfo.setFont(font)
        self.pushButtonInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonInfo.setStyleSheet("background: qlineargradient(spread:pad, x1:0.521263, y1:1, x2:0.505, y2:0.102, stop:0.00526316 rgba(148, 148, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"/*background-color:white;*/\n"
"border-radius: 5%;")
        self.pushButtonInfo.setObjectName("pushButtonInfo")
        self.horizontalLayout_7.addWidget(self.pushButtonInfo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(40, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.labelId = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelId.setFont(font)
        self.labelId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelId.setObjectName("labelId")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelId)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.labelVariedad = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariedad.setFont(font)
        self.labelVariedad.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariedad.setObjectName("labelVariedad")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelVariedad)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.labelConteo = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelConteo.setFont(font)
        self.labelConteo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelConteo.setObjectName("labelConteo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelConteo)
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.labelMaduros = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMaduros.setFont(font)
        self.labelMaduros.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaduros.setObjectName("labelMaduros")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelMaduros)
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.labelNomaduros = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNomaduros.setFont(font)
        self.labelNomaduros.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNomaduros.setObjectName("labelNomaduros")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelNomaduros)
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.labelAreaCrudo = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAreaCrudo.setFont(font)
        self.labelAreaCrudo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAreaCrudo.setObjectName("labelAreaCrudo")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelAreaCrudo)
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.labelAreaQuemado = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAreaQuemado.setFont(font)
        self.labelAreaQuemado.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAreaQuemado.setObjectName("labelAreaQuemado")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.labelAreaQuemado)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonResultados = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonResultados.setEnabled(True)
        self.pushButtonResultados.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButtonResultados.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonResultados.setFont(font)
        self.pushButtonResultados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonResultados.setStyleSheet("background: qlineargradient(spread:pad, x1:0.521263, y1:1, x2:0.505, y2:0.102, stop:0.00526316 rgba(148, 148, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"/*background-color:white;*/\n"
"border-radius: 5%;")
        self.pushButtonResultados.setObjectName("pushButtonResultados")
        self.horizontalLayout_6.addWidget(self.pushButtonResultados)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.widget_5.setFont(font)
        self.widget_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(20, 10, -1, 50)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButtonStart = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonStart.setEnabled(False)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(250, 100))
        self.pushButtonStart.setMaximumSize(QtCore.QSize(250, 16777215))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.547, 0.983, 0.532105, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0684211, QtGui.QColor(0, 157, 0))
        gradient.setColorAt(1.0, QtGui.QColor(185, 244, 158))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButtonStart.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStart.setFont(font)
        self.pushButtonStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonStart.setMouseTracking(False)
        self.pushButtonStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonStart.setAutoFillBackground(False)
        self.pushButtonStart.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.547, y1:0.983, x2:0.532105, y2:0, stop:0.0684211 rgba(0, 157, 0, 255), stop:1 rgba(185, 244, 158, 255));\n"
"border-radius: 15%;")
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout_10.addWidget(self.pushButtonStart)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.frame = QtWidgets.QFrame(self.widget_5)
        self.frame.setMaximumSize(QtCore.QSize(123123, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonHome = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonHome.setEnabled(False)
        self.pushButtonHome.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButtonHome.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonHome.setFont(font)
        self.pushButtonHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonHome.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonHome.setStyleSheet("background: qlineargradient(spread:pad, x1:0.521263, y1:1, x2:0.505, y2:0.102, stop:0.00526316 rgba(148, 148, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"/*background-color:white;*/\n"
"border-radius: 5%;\n"
"/*border:2px solid black;*/")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Resources/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHome.setIcon(icon)
        self.pushButtonHome.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.horizontalLayout_8.addWidget(self.pushButtonHome)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.frame_5 = QtWidgets.QFrame(self.widget_5)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButtonCalibracion = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonCalibracion.setEnabled(False)
        self.pushButtonCalibracion.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButtonCalibracion.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCalibracion.setFont(font)
        self.pushButtonCalibracion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCalibracion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonCalibracion.setStyleSheet("background: qlineargradient(spread:pad, x1:0.521263, y1:1, x2:0.505, y2:0.102, stop:0.00526316 rgba(148, 148, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"/*background-color:white;*/\n"
"border-radius: 5%;\n"
"/*border:2px solid black;*/")
        self.pushButtonCalibracion.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonCalibracion.setObjectName("pushButtonCalibracion")
        self.horizontalLayout_11.addWidget(self.pushButtonCalibracion)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelDisplay = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDisplay.sizePolicy().hasHeightForWidth())
        self.labelDisplay.setSizePolicy(sizePolicy)
        self.labelDisplay.setMinimumSize(QtCore.QSize(600, 600))
        self.labelDisplay.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.labelDisplay.setStyleSheet("background-color: gray;")
        self.labelDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelDisplay.setLineWidth(10)
        self.labelDisplay.setText("")
        self.labelDisplay.setScaledContents(True)
        self.labelDisplay.setObjectName("labelDisplay")
        self.horizontalLayout_2.addWidget(self.labelDisplay)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1525, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cutting Vision"))
        self.label.setText(_translate("MainWindow", "INFORMACION DEL COSECHADOR"))
        self.label_8.setText(_translate("MainWindow", "ID COSECHADOR"))
        self.label_5.setText(_translate("MainWindow", "VARIEDAD"))
        self.comboBoxVariedad.setItemText(0, _translate("MainWindow", "Báltica"))
        self.comboBoxVariedad.setItemText(1, _translate("MainWindow", "Bonita"))
        self.comboBoxVariedad.setItemText(2, _translate("MainWindow", "Sunny"))
        self.pushButtonInfo.setText(_translate("MainWindow", "Enviar"))
        self.label_6.setText(_translate("MainWindow", "Datos del proceso"))
        self.label_13.setText(_translate("MainWindow", "Cosechador"))
        self.labelId.setText(_translate("MainWindow", "Ingresa ID"))
        self.label_9.setText(_translate("MainWindow", "Variedad"))
        self.labelVariedad.setText(_translate("MainWindow", "Ingresa Variedad"))
        self.label_14.setText(_translate("MainWindow", "Conteo"))
        self.labelConteo.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "%Maduros"))
        self.labelMaduros.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "%No Maduros"))
        self.labelNomaduros.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "..."))
        self.labelAreaCrudo.setText(_translate("MainWindow", "..."))
        self.label_20.setText(_translate("MainWindow", "..."))
        self.labelAreaQuemado.setText(_translate("MainWindow", "..."))
        self.pushButtonResultados.setText(_translate("MainWindow", "Resultados"))
        self.pushButtonStart.setText(_translate("MainWindow", "SCAN"))
        self.pushButtonHome.setText(_translate("MainWindow", " HOME"))
        self.pushButtonCalibracion.setText(_translate("MainWindow", "CALIBRACION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

